### ISSUE TITLE
Extraction APK file name from $BITRISE_APK_PATH

### ISSUE THREAD

**Issue by michaudhugo** [thefuntasty/bitrise-step-apk-info#1]
Dear @radimvaculik ,

Do you think it's possible to add one environment variable to the output of this bitrise step?

It would be great if it could generates as well the APK file name, using the $BITRISE_APK_PATH from Gradle runner task. Such as /bitrise/deploy/myAPK.apk => myAPK.apk

I'm looking forward hearing from you :)

**Comment by radimvaculik** [comment]
Hello @michaudhugo, 

you can do it easily with custom script on Bitrise:

```sh
$ basename ~/Downloads/Projects/Folder/myfile.apk
myfile.apk
```

Regards,
Radim
