### ISSUE TITLE
APK file size as MB

### ISSUE THREAD

**Issue by mertceyhan** [thefuntasty/bitrise-step-apk-info#16]
How can we use `$ANDROID_APK_FILE_SIZE` variable as MB?

**Comment by skywall** [comment]
@mertceyhan You can add the Script step and format file size as you wish. Something like this should work in theory (I haven't tested it):
```bash
#!/bin/sh

APK_SIZE_IN_MB=$(echo "scale=2;$ANDROID_APK_FILE_SIZE / 1000000"  | bc)
echo $APK_SIZE_IN_MB
envman add --key APK_FILE_SIZE_MB --value $APK_SIZE_IN_MB
```
