### ISSUE TITLE
Error when app name contains a quote

### ISSUE THREAD

**Issue by raphaelappsolute** [thefuntasty/bitrise-step-apk-info#2]
When launching this step with an app name containing a quote, the following error happens : 
sh: 1: Syntax error: Unterminated quoted string
Failed to export ANDROID_APP_NAME

**Comment by radimvaculik** [comment]
Hello @raphaelappsolute. Thanks for report. We will fix it in 2 weeks.

**Comment by radimvaculik** [comment]
Fixed @ b8763ea4d0
